config/routes.rb
Rails.application.routes.draw do
  resources :info_requests, only: [:new, :create]

	root 'static#home'
	get '/services' => 'static#services'
	get '/products' => 'static#products'
	get '/about' => 'static#about'

	#resources :institutions, 

	#devise_for :users, :controllers => {:registrations => 'custom_devise/registrations'} 


  # get 'signin' => 'devise/sessions#new', :as => :new_user_session
  # post 'signin' => 'devise/sessions#create', :as => :user_session
  # match 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session,
  #   :via => Devise.mappings[:user].sign_out_via
  
end

app/models/info_request.rb
class InfoRequest < ActiveRecord::Base
end

app/models/institution.rb
class Institution < ActiveRecord::Base
end

app/models/interest.rb
class Interest < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable

	has_one :interest

	TEMPP = "05e513ffa7f54e51"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_filter :user_layout

	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

private

	def user_layout
		'static'
	# 	if user_signed_in?
	# 		'application'
	# 	else
	# 		'static'
	# 	end
	end
end

app/controllers/custom_devise/registrations_controller.rb
class CustomDevise::RegistrationsController < Devise::RegistrationsController
	layout 'static'
	

	def create
		# super
		# @success = false
		params = sign_up_params
		params[:password] = User::TEMPP
		params[:password_confirmation] = User::TEMPP

		@user = User.new(params)

		i = Interest.new(interest_params)

		puts "#{i.degree_mapping}"

		@user.interest = i

    		# r = build_resource(params)

    		# r.interest.new params[:interests]

    		# stop

		if @user.save
     			set_flash_message :notice, :signed_up
			@institution = Institution.new(institution_params)
			@institution.save!
			@success = true
   		 else
			clean_up_passwords(resource)
			#render 'static/home', :anchor => "sign_up"
    		end
	end

	
	def destroy
		super
	end


private
	def sign_up_params
		params.require(:user).permit(:name, :phone, :email, :title, :password, :password_confirmation)
	end

	def institution_params
		params.require(:institution).permit(:name, :code, :street, :address, :city, :zip, :phone)
	end

	def interest_params
		params.require(:interest).permit(:sankey, :degree_mapping, :analytic_dashboards, :datamart, :custom_dashboards)
	end
end

app/controllers/info_requests_controller.rb
require 'httparty'

class InfoRequestsController < ApplicationController
	before_action :set_info_request, only: [:show, :edit, :update, :destroy]

	respond_to :html, :js

	def index
		@info_requests = InfoRequest.all
		respond_with(@info_requests)
	end

	def show
		respond_with(@info_request)
	end

	def new
		@info_request = InfoRequest.new
		respond_with(@info_request)
	end

	def edit
	end

	def create
		@info_request = InfoRequest.new(info_request_params)
		@info_request.save

		description = ""

		json = JSON.parse @info_request.to_json
		json.delete "id"
		json.delete "updated_at"
		a = json.to_a
		a.each do |x|
			description += "#{x[0]}: #{x[1]}\n"
		end

		body = {
			"key" => "dd3759f01960017f7897f1abf800eb273a2b2e52",
			"issue" => {
				"project_id" => 1,
				"tracker_id" => 3,
				"status_id" => 1,
				"priority_id" => 2,
				"subject" => "Request from #{@info_request.institution}",
				"description" => description
			}
		}

		HTTParty.post("http://52.26.168.38/issues.json", body: body)

		respond_with(@info_request)
	end

	def update
		@info_request.update(info_request_params)
		respond_with(@info_request)
	end

	def destroy
		@info_request.destroy
		respond_with(@info_request)
	end

	private
		def set_info_request
			@info_request = InfoRequest.find(params[:id])
		end

		def info_request_params
			params.require(:info_request).permit(:name, :email, :institution, :title, :phone, :comments, :sankey, :degree_mapping, :analytic_dashboards, :datamart, :custom_dashboards)
		end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
	before_action :set_institution, only: [:show, :edit, :update, :destroy]

	# GET /institutions
	# GET /institutions.json
	def index
		@institutions = Institution.all
	end

	# GET /institutions/1
	# GET /institutions/1.json
	def show
	end

	# GET /institutions/new
	def new
		@institution = Institution.new
	end

	# GET /institutions/1/edit
	def edit
	end

	# POST /institutions
	# POST /institutions.json
	def create
		@institution = Institution.new(institution_params)

		respond_to do |format|
			if @institution.save
				format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
				format.json { render :show, status: :created, location: @institution }
			else
				format.html { render :new }
				format.json { render json: @institution.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /institutions/1
	# PATCH/PUT /institutions/1.json
	def update
		respond_to do |format|
			if @institution.update(institution_params)
				format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
				format.json { render :show, status: :ok, location: @institution }
			else
				format.html { render :edit }
				format.json { render json: @institution.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /institutions/1
	# DELETE /institutions/1.json
	def destroy
		@institution.destroy
		respond_to do |format|
			format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_institution
			@institution = Institution.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def institution_params
			params.require(:institution).permit(:name, :code, :street, :address, :city, :zip, :phone)
		end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def home

	end

	def about

	end

	def services
	end

	def products
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_requests_helper.rb
module InfoRequestsHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/info_requests/_form.html.erb
<section id="info-request">
	<div id="request-close"><i class="fa fa-times"></i></div>         
	
	<div id='get-started-info'>
		<h1>Information Request</h1>
		<p>To get started using our products and services, please provide the information listed below and you will be contacted shortly.</p>
	</div>                    
	
	<div id="info-request-form">
		<%= form_for(@info_request, remote: true) do |f| %>
			<ul id='sign-up-errors'>
				<% resource.errors.full_messages.each do |e| %>
					<li><%= e %></li>
				<% end %>
			</ul>

			<div class='container'>
				<div class='short-field column-6'>
					<%= f.label :name %>
					<%= f.text_field :name %>
				</div>

				<div class='short-field column-6'>
					<%= f.label :title %>
					<%= f.text_field :title %>
				</div>
			</div>

			<div class='container'>
				<div class='short-field column-6'>
					<%= f.label :email %>
					<%= f.text_field :email %>
				</div>

				<div class='short-field column-6'>
					<%= f.label :phone %>
					<%= f.text_field :phone %>
				</div>
			</div>

			<%= fields_for :institution do |i| %>
				<div id='institution-name-field' class="long-field">
					<%= f.label 'Institution' %>
					<%= f.text_field :institution, autocomplete: "off"%>
				</div>
			<% end %>

			Which products and services are you interested in?
			<div class='container'>
				<div class="interest-box">
					<label>Student Flow Sankey Diagrams</label>
					<%= f.check_box :sankey %>
				</div>

				<div class="interest-box">
					<label>Degree Mapping and Student Tracking</label>
					<%= f.check_box :degree_mapping %>
				</div>

				<div class="interest-box">
					<label>Analytic Dashboards</label>
					<%= f.check_box :analytic_dashboards %>
				</div>

				<div class="interest-box">
					<label>Datamarts</label>
					<%= f.check_box :datamart %>
				</div>

				<div class="interest-box">
					<label>Custom Dashboards</label>
					<%= f.check_box :custom_dashboards %>
				</div>
			</div>

			<br>

			<%= f.submit "SUBMIT REQUEST", id: 'request-button' %>
		<% end %>
	</div>

</section>

app/views/info_requests/create.js.erb
$("#get-started-info h1").html("Thank You");
$("#get-started-info p").remove();
$("#info-request-form").html("<p>Thank you for your interest in Academic Dashboards. We will contact you soon to get you started on our platform.</p>");

app/views/info_requests/edit.html.erb
<h1>Editing info_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @info_request %> |
<%= link_to 'Back', info_requests_path %>

app/views/info_requests/index.html.erb
<h1>Listing info_requests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Institution</th>
      <th>Title</th>
      <th>Phone</th>
      <th>Comments</th>
      <th>Sankey</th>
      <th>Degree mapping</th>
      <th>Analytic dashboards</th>
      <th>Datamart</th>
      <th>Custom dashboards</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @info_requests.each do |info_request| %>
      <tr>
        <td><%= info_request.name %></td>
        <td><%= info_request.email %></td>
        <td><%= info_request.institution %></td>
        <td><%= info_request.title %></td>
        <td><%= info_request.phone %></td>
        <td><%= info_request.comments %></td>
        <td><%= info_request.sankey %></td>
        <td><%= info_request.degree_mapping %></td>
        <td><%= info_request.analytic_dashboards %></td>
        <td><%= info_request.datamart %></td>
        <td><%= info_request.custom_dashboards %></td>
        <td><%= link_to 'Show', info_request %></td>
        <td><%= link_to 'Edit', edit_info_request_path(info_request) %></td>
        <td><%= link_to 'Destroy', info_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Info request', new_info_request_path %>

app/views/info_requests/new.js.erb
var form = $("<%=j render 'form' %>");

$('body').css('overflow', 'hidden');
$('body').prepend($("<div id='screen'></div>"));

$('body').prepend(form);

$('#slideout').removeClass('is-visible');
$('#nav-screen').removeClass('is-visible');

app/views/info_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @info_request.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @info_request.email %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @info_request.institution %>
</p>

<p>
  <strong>Title:</strong>
  <%= @info_request.title %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @info_request.phone %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @info_request.comments %>
</p>

<p>
  <strong>Sankey:</strong>
  <%= @info_request.sankey %>
</p>

<p>
  <strong>Degree mapping:</strong>
  <%= @info_request.degree_mapping %>
</p>

<p>
  <strong>Analytic dashboards:</strong>
  <%= @info_request.analytic_dashboards %>
</p>

<p>
  <strong>Datamart:</strong>
  <%= @info_request.datamart %>
</p>

<p>
  <strong>Custom dashboards:</strong>
  <%= @info_request.custom_dashboards %>
</p>

<%= link_to 'Edit', edit_info_request_path(@info_request) %> |
<%= link_to 'Back', info_requests_path %>

app/views/institutions/_form.html.erb
<%= form_for(@institution) do |f| %>
	<% if @institution.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

			<ul>
			<% @institution.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :code %><br>
		<%= f.text_field :code %>
	</div>
	<div class="field">
		<%= f.label :street %><br>
		<%= f.text_field :street %>
	</div>
	<div class="field">
		<%= f.label :address %><br>
		<%= f.text_field :address %>
	</div>
	<div class="field">
		<%= f.label :city %><br>
		<%= f.text_field :city %>
	</div>
	<div class="field">
		<%= f.label :zip %><br>
		<%= f.text_field :zip %>
	</div>
	<div class="field">
		<%= f.label :phone %><br>
		<%= f.text_field :phone %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/institutions/edit.html.erb
<h1>Editing institution</h1>

<%= render 'form' %>

<%= link_to 'Show', @institution %> |
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<h1>Listing institutions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Street</th>
      <th>Address</th>
      <th>City</th>
      <th>Zip</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @institutions.each do |institution| %>
      <tr>
        <td><%= institution.name %></td>
        <td><%= institution.code %></td>
        <td><%= institution.street %></td>
        <td><%= institution.address %></td>
        <td><%= institution.city %></td>
        <td><%= institution.zip %></td>
        <td><%= institution.phone %></td>
        <td><%= link_to 'Show', institution %></td>
        <td><%= link_to 'Edit', edit_institution_path(institution) %></td>
        <td><%= link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institution', new_institution_path %>

app/views/institutions/new.html.erb
<h1>New institution</h1>

<%= form_for(@institution) do |f| %>
	<% if @institution.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

			<ul>
			<% @institution.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :code %><br>
		<%= f.text_field :code %>
	</div>
	<div class="field">
		<%= f.label :street %><br>
		<%= f.text_field :street %>
	</div>
	<div class="field">
		<%= f.label :address %><br>
		<%= f.text_field :address %>
	</div>
	<div class="field">
		<%= f.label :city %><br>
		<%= f.text_field :city %>
	</div>
	<div class="field">
		<%= f.label :zip %><br>
		<%= f.text_field :zip %>
	</div>
	<div class="field">
		<%= f.label :phone %><br>
		<%= f.text_field :phone %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/institutions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @institution.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @institution.code %>
</p>

<p>
  <strong>Street:</strong>
  <%= @institution.street %>
</p>

<p>
  <strong>Address:</strong>
  <%= @institution.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @institution.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @institution.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @institution.phone %>
</p>

<%= link_to 'Edit', edit_institution_path(@institution) %> |
<%= link_to 'Back', institutions_path %>

app/views/layouts/_nav.html.erb
<ul>
	<li><%= link_to 'About Us', '/about' %></li>
	<li><%= link_to 'Products', '/products' %></li>
	<li><%= link_to 'Services', '/services' %></li>
	<li><%= link_to 'Get Started', '/info_requests/new', class: 'get-started', remote: true %></li>
</ul>

app/views/layouts/_sign_in.html.erb
<div id='sign-in-form'>
	<%= form_for(:user, :url => session_path(:user)) do |f| %>
	  <div id='email' class='sign-in-field'>
			<%= f.label :email %><br />
			<%= f.email_field :email, autofocus: true %><br />
			<%= f.check_box :remember_me %> 
			<%= f.label :remember_me, :id => 'remember-me-label' %>
		</div>

	  <div id='password' class='sign-in-field'>
			<%= f.label :password %><br />
			<%= f.password_field :password, autocomplete: "off" %><br />
			<%= link_to "Forgot your password?", new_password_path(:user) %>
		</div>

	  <div id='submit'><%= f.submit "Sign in" ,id:'sign-in-button'%></div>
	<% end %>
</div>

app/views/layouts/_sign_up.html.erb
<div id="info-request">
		<%= form_for(@inforequest) do |f| %>
			<ul id='sign-up-errors'>
				<% resource.errors.full_messages.each do |e| %>
					<li><%= e %></li>
				<% end %>
			</ul>

			<div class='container'>
				<div class='short-field column-6'>
					<%= f.label :name %>
					<%= f.text_field :name %>
				</div>

				<div class='short-field column-6'>
					<%= f.label :title %>
					<%= f.text_field :title %>
				</div>
			</div>

			<div class='container'>
				<div class='short-field column-6'>
					<%= f.label :email %>
					<%= f.text_field :email %>
				</div>

				<div class='short-field column-6'>
					<%= f.label :phone %>
					<%= f.text_field :phone %>
				</div>
			</div>

			<%= fields_for :institution do |i| %>
				<div id='institution-name-field' class="long-field">
					<%= f.label 'Institution' %>
					<%= f.text_field :institution, autocomplete: "off"%>
				</div>
			<% end %>

			Which services are you interested in?
			<div class='container'>
				<div class="interest-box">
					<label>Student Flow Sankey Diagrams</label>
					<%= f.check_box :sankey %>
				</div>

				<div class="interest-box">
					<label>Degree Mapping and Student Tracking</label>
					<%= f.check_box :degree_mapping %>
				</div>

				<div class="interest-box">
					<label>Analytic Dashboards</label>
					<%= f.check_box :analytic_dashboards %>
				</div>

				<div class="interest-box">
					<label>Datamarts</label>
					<%= f.check_box :datamart %>
				</div>

				<div class="interest-box">
					<label>Custom Dashboards</label>
					<%= f.check_box :custom_dashboards %>
				</div>
			</div>

			<!--
			<div class='container'>
				<div class='short-field column-6'>
					<%= f.label :password %>
					<%= f.password_field :password, autocomplete: "off" %>
				</div>

				<div class='short-field column-6'>
					<%= f.label :password_confirmation %>
					<%= f.password_field :password_confirmation, autocomplete: "off" %>
				</div>
			</div>
			-->

			<br>

			<%= f.submit "SIGN UP", id: 'sign-up-button' %>
		<% end %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AcademicDashboards</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>

</body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>AcademicDashboards</title>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,700' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,300' rel='stylesheet' type='text/css'>
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	<%= csrf_meta_tags %>

	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-61215871-1', 'auto');
		ga('send', 'pageview');
	</script>
	
</head>
<body>

	<header id="static-header">
		<div class="container">
			<div id="logo">
				<%= link_to image_tag('ad_logo_web.png', height: '60px'), '/', id: 'desktop-logo' %>
				<%= link_to image_tag('ad_logo_mobile.png', height: '60px'), '/', id: 'mobile-logo' %>
				<!--<%= link_to 'Academic Dashboards', '/' %>-->
			</div>
			
			<nav id="static-nav">
				<%= render 'layouts/nav' %>
				<a id="nav-trigger"><i class="fa fa-bars"></i></a>
			</nav>
		</div>
	</header>

	<nav id="slideout">
		<%= render 'layouts/nav' %>
	</nav>
	<div id="nav-screen"></div>

	<%= yield %>

	<footer>
		<h3>Academic Dashboards</h3>
		<span>© 2014 Academic Dashboards. All Rights Reserved</span>
	</footer>

</body>
</html>